Restoring modules from user's shuying
Python 3.9.13
Traceback (most recent call last):
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
Traceback (most recent call last):
  File "/scratch/user/zshuying/ppi_mutation/scripts/clinvar_variant_sum.py", line 5, in <module>
    from utils import *
  File "/scratch/user/zshuying/ppi_mutation/scripts/utils.py", line 16, in <module>
    from matplotlib_venn import venn3, venn3_circles,venn3_unweighted
ModuleNotFoundError: No module named 'matplotlib_venn'
srun: error: tnxt-0457: tasks 0-27: Exited with exit code 1
